# Generated by Django 3.1.7 on 2022-07-24 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_name', models.CharField(max_length=255)),
                ('td_description', models.TextField(max_length=1000)),
                ('td_date_created', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['id'],
            },
        ),
    ]
