# Generated by Django 3.1.7 on 2022-07-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produt',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
