# Generated by Django 3.1.7 on 2022-07-23 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_first_name', models.CharField(max_length=255)),
                ('us_last_name', models.CharField(max_length=255)),
                ('us_email', models.EmailField(max_length=255, unique=True)),
                ('us_dni', models.IntegerField()),
                ('us_password', models.CharField(max_length=255)),
                ('us_date_created', models.DateField(default=datetime.datetime.now)),
                ('us_is_activate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
